force-app/main/default/objects/Case/fields/Actual_Parent_Type__c.field-meta.xml
<CustomField>
    <fullName>Actual_Parent_Type__c</fullName>
    <label>Actual Parent Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Actual_Type__c.field-meta.xml
<CustomField>
    <fullName>Actual_Type__c</fullName>
    <label>Actual Type</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Parent_Type__c.field-meta.xml
<CustomField>
    <fullName>Parent_Type__c</fullName>
    <label>Parent Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GARBAGE</fullName>
            </value>
            <value>
                <fullName>BLIGHTED PROPERTIES</fullName>
            </value>
            <value>
                <fullName>STREET/TRAFFIC ISSUES</fullName>
            </value>
            <value>
                <fullName>RECYCLING</fullName>
            </value>
            <value>
                <fullName>SEWER/WASTEWATER</fullName>
            </value>
            <value>
                <fullName>ROAD MAINTENANCE ISSUES</fullName>
            </value>
            <value>
                <fullName>DRAINAGE, EROSION, FLOODING OR HOLES</fullName>
            </value>
            <value>
                <fullName>MOWING AND TREE ISSUES</fullName>
            </value>
            <value>
                <fullName>BUILDING CODE/ZONING VIOLATIONS</fullName>
            </value>
            <value>
                <fullName>ENVIRONMENTAL ISSUES</fullName>
            </value>
            <value>
                <fullName>NEIGHBORHOOD/SUBDIVISION ISSUES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parent_Type__c/Parent_Type__c.object-meta.xml
<CustomObject>
    <label>Parent Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parent Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchCaseInserter.cls
global class BatchCaseInserter implements Database.Batchable<SObject> {
    global Database.QueryLocator start(Database.BatchableContext bc) 
    {
        //Take up to 1000 Closed cases with Parent and Issue Type already populated
        String query = 'SELECT Subject,Description,Parent_Type__c, Type FROM Case Where Status=\'Closed\' and Type!=null and Parent_Type__c!=null LIMIT 1000';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Case> cases)
    {
        List<Case> newCases = new List<Case>();
        for (Case c:cases)
        {
            //'Clone' Them (and store the actual so that we can compare against prediction later)
            Case newCase = new Case(
                Description=c.Description,Subject=c.Subject,
                Actual_Parent_Type__c = c.Parent_Type__c,
                Actual_Type__c = c.Type,
				Parent_Type__c='',
                Type='',
				Status='New');
            newCases.add(newCase);
        }
        insert newCases;
    }
    global void finish(Database.BatchableContext bc)
    {
        
    }
}