force-app/main/default/objects/Case/fields/Actual_Parent_Type__c.field-meta.xml
<CustomField>
    <fullName>Actual_Parent_Type__c</fullName>
    <label>Actual Parent Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Actual_Type__c.field-meta.xml
<CustomField>
    <fullName>Actual_Type__c</fullName>
    <label>Actual Type</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Parent_Type__c.field-meta.xml
<CustomField>
    <fullName>Parent_Type__c</fullName>
    <label>Parent Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GARBAGE</fullName>
            </value>
            <value>
                <fullName>BLIGHTED PROPERTIES</fullName>
            </value>
            <value>
                <fullName>STREET/TRAFFIC ISSUES</fullName>
            </value>
            <value>
                <fullName>RECYCLING</fullName>
            </value>
            <value>
                <fullName>SEWER/WASTEWATER</fullName>
            </value>
            <value>
                <fullName>ROAD MAINTENANCE ISSUES</fullName>
            </value>
            <value>
                <fullName>DRAINAGE, EROSION, FLOODING OR HOLES</fullName>
            </value>
            <value>
                <fullName>MOWING AND TREE ISSUES</fullName>
            </value>
            <value>
                <fullName>BUILDING CODE/ZONING VIOLATIONS</fullName>
            </value>
            <value>
                <fullName>ENVIRONMENTAL ISSUES</fullName>
            </value>
            <value>
                <fullName>NEIGHBORHOOD/SUBDIVISION ISSUES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parent_Type__c/Parent_Type__c.object-meta.xml
<CustomObject>
    <label>Parent Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parent Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CloseSomeCases.cls
public class CloseSomeCases {
    
    @AuraEnabled
    public static void closeSomeCases() {
        List<case> cases = [select id, actual_parent_type__c,actual_type__c,  parent_type__c, type, status from Case where status='New' limit 2000];

        List<String> parentTypes = new List<String>{'ROAD MAINTENANCE ISSUES','GARBAGE','RECYCLING','MOWING AND TREE ISSUES'};
        List<String> caseTypes = new List<String>{'DAMAGED GARBAGE CART','MISSED WOODY WASTER SERVICE','TALL GRASS','STREET LIGHT OUTAGE OR DAMAGE'};
        
        Integer actualtypesUsed = 0;
        Integer randomtypesUsed = 0;
        
        for (Case c: cases) {
            if (Math.random() <= 0.85) {
                c.parent_type__c = c.actual_parent_type__c;
                c.Type = c.actual_type__c;
                actualtypesUsed++;
            } else {
                Double randomNumber = Math.random(); 
                Integer arrayLength = 4; 
                Integer randomIndex = (randomNumber *(arrayLength-1)).intValue();
                
                c.parent_type__c = parentTypes[randomIndex];
                c.Type = caseTypes[randomIndex];
                randomtypesUsed++;
            }
             c.Status = 'Closed';
        }
        
        System.debug(actualtypesUsed);
        System.debug(randomtypesUsed);
        if (cases!=null && cases.size() > 0) {
            update cases;    
        }
        
    }

}